language: python
python:
    - "3.5"
install:
    - pip install -r requirements.txt
    - pip install -e .[test]
env:
    - THEANO_FLAGS=floatX=float32
    - THEANO_FLAGS=floatX=float64
script: pytest
